### PR TITLE
Help text

### PR DESCRIPTION
**Pull request by Stephen-Gates**
I've made a start on improving the help. 
- I had to add a missing file for the Unique Field error message - schema_006.md 
- Some help files are missing e.g. http_404_error which was referenced when I ran [this test](http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fraw.githubusercontent.com%2FStephen-Gates%2FGTFS%2Fmaster%2Ftests%2Fcalendar_dates.txt&format=csv&encoding=&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FStephen-Gates%2FGTFS%2Fmaster%2Fschemas%2Fcalendar_dates-schema.json). 
- Some errors seems to be duplicates and perhaps both messages don't need to be reported e.g. [This test](http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fraw.githubusercontent.com%2FStephen-Gates%2FGTFS%2Fmaster%2Ftests%2Ffeed_info.txt&format=csv&encoding=&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FStephen-Gates%2FGTFS%2Fmaster%2Fschemas%2Ffeed_info-schema.json) reports both Defective Row (Structure_003.md) and Incorrect Dimensions (Schema_002.md). I made the help text the same for these messages.

image

I will try invoke more errors using various test data so I can more help text. Any pointers are welcome.

### CODE REVIEW

**Comment by pwalsh** [comment]
@Stephen-Gates this is great!

For your information, we are refactoring and relaunching a very powerful set of improvements on GoodTables by end of 2016. 

We are also extracting out everything we've learned about tabular data errors into a standalone spec that will be used in GoodTables and other projects: [data-quality-spec](https://github.com/frictionlessdata/data-quality-spec). 

Feel free to keep contributing on this repo: @roll will merge in changes as they land, and also ensure that the extra help info gets passed forward to the new library-agnostic spec.

**Comment by Stephen-Gates** [comment]
@pwalsh happy to help. 

 I've found:
-  the structure errors 001..006 in [structure.py](https://github.com/frictionlessdata/goodtables/blob/master/goodtables/processors/structure.py)
- the schema errors 001..008 in [schema.py](https://github.com/frictionlessdata/goodtables/blob/master/goodtables/processors/schema.py)
- the table schema errors 050..084 in [table_schema.py](https://github.com/frictionlessdata/goodtables/blob/master/goodtables/utilities/table_schema.py)

I can work my way through these.

Where do I find the other errors and what should I call the help files? E.g. 
- there's a schema_085 in the [help files](https://github.com/frictionlessdata/goodtables-web/tree/master/web/theme/templates/pages/help) - what's it for?
- errors for missing data file, missing schema file
- data is html or zip

I will try and resist adding humour about the importance of commas...

_I love my parents, Kylie Minogue and Kermit the Frog._

**Comment by pwalsh** [comment]
comma humour great!

**Comment by Stephen-Gates** [comment]
Wont be adding anymore to this PR. I don't understand the errors raised by schema_005, 007, 008 which are the last three shown on the help page.

**Comment by roll** [comment]
@Stephen-Gates 
thanks!

**Pull request merged**
