### PR TITLE
Example CSV loading per #48

### PR DESCRIPTION
**Pull request by danfowler**

### CODE REVIEW

**Comment by pwalsh** [comment]
@danfowler thanks. Do you also have access to deploy?

**Comment by danfowler** [comment]
Hi @pwalsh thanks! I have no access to this repo.

**Comment by pwalsh** [comment]
@danfowler I've added you as a collaborator on Heroku. Would you be able to see if you can push this?

**Comment by danfowler** [comment]
Hi @pwalsh! I have access and have just pushed.

**Pull request merged**
